/**
 * Live-simulation chat contracts. These describe the realtime session the
 * frontend runs over Socket.IO against the NestJS `ChatGateway`.
 *
 * Event names + payloads are kept 1:1 with the backend gateway/service so the
 * socket layer and the gateway stay compatible:
 *   emit  "start_session"  { specialty }          → server generates a patient
 *   emit  "chat_message"   "<text>"               → server streams a reply
 *   on    "session_started"{ message, vitals }     (patient ready + opener)
 *   on    "chat:chunk"     { chunk }               (streamed reply token)
 *   on    "chat:done"      { done: true }          (reply complete)
 *   on    "chat:error"     { message }             (per-message failure)
 *   on    "error"          "<reason>"              (auth/connection failure)
 */

/** Who authored a chat bubble. */
export type ChatRole = 'doctor' | 'patient' | 'system'

export interface ChatMessage {
  id: string
  role: ChatRole
  content: string
  /** True while the patient reply is still streaming in. */
  pending?: boolean
  /** Epoch ms; used for ordering and timestamps. */
  timestamp: number
}

/**
 * Session lifecycle as seen by the UI:
 *   idle        nothing started yet
 *   connecting  opening the socket / authenticating
 *   generating  connected, patient is being generated by the AI (show loader)
 *   active      patient ready, chat is live (heartbeat animates)
 *   ended       session closed by the user
 *   error       connection/auth failure
 */
export type SessionPhase =
  | 'idle'
  | 'connecting'
  | 'generating'
  | 'active'
  | 'ended'
  | 'error'

/**
 * Specialty values accepted by the backend `start_session` event. These mirror
 * `SessionSpecialtyEnum` on the server exactly — the dashboard's lowercase ids
 * (e.g. "cardiology") are mapped to these before emitting.
 */
export type SessionSpecialty =
  | 'TRAUMATOLOGY'
  | 'CARDIOLOGY'
  | 'EMERGENCY_MEDICINE'

/** Payload for the `start_session` event (mirrors backend StartSessionDto). */
export interface StartSessionPayload {
  specialty: SessionSpecialty
}

/**
 * The generated patient's profile + live vitals (mirrors backend
 * `PatientVitalsType`). `condition`, `answerAccuracy` and `shortFeedback` are
 * evaluation fields — the UI deliberately does NOT surface them during the
 * consultation so the trainee has to reach the diagnosis themselves.
 */
export interface PatientVitals {
  patientName: string
  patientAge: number
  patientGender: string
  weight: number
  knownAllergies: string
  condition: string
  heartRate: number
  bloodPressure: string
  spO2: number
  painLevel: number
  patientStatus: string
  answerAccuracy: number
  shortFeedback: string
}

/** Payload for the `session_started` event once the patient is generated. */
export interface SessionStartedPayload {
  /** The patient's opening line, shown as the first patient message. */
  message: string
  vitals: PatientVitals
}

/** A one-tap clinical prompt shown above the composer. */
export interface QuickAction {
  id: string
  /** Short button label. */
  label: string
  /** The doctor message sent when the action is tapped. */
  prompt: string
  /** Key into the icon set rendered by QuickActions. */
  icon: 'history' | 'vitals' | 'pain' | 'meds' | 'exam' | 'labs'
}
