/**
 * Live-simulation chat contracts. These describe the realtime session the
 * frontend runs over Socket.IO against the NestJS `ChatGateway`.
 *
 * Event names + payloads are kept 1:1 with the backend gateway/service so the
 * socket layer and the gateway stay compatible:
 *   emit  "start_session"  { specialty }              → generate a patient
 *   emit  "chat_message"   "<text>"                   → ask the patient
 *   emit  "final_diagnosis""<text>"                   → save the working diagnosis
 *   on    "session_started"{ message, patient }        (patient ready + opener)
 *   on    "chat:done"      { outputMessage, patient }  (reply + updated vitals)
 *   on    "chat:error"     { message }                 (per-message failure)
 *   on    "error"          "<reason>"                  (auth/connection failure)
 *
 *   emit  "session_end"    (none)                     → request the analysis
 *   on    "session:end"    { response, scores }        (final report)
 *
 * The final diagnosis is editable for the whole session; each submit pushes the
 * latest text to the server, which persists it when the socket disconnects.
 * Ending requests the server analysis first, then we close the socket.
 */

/** Who authored a chat bubble. */
export type ChatRole = 'doctor' | 'patient' | 'system'

export interface ChatMessage {
  id: string
  role: ChatRole
  content: string
  /** True while the patient reply is still streaming in. */
  pending?: boolean
  /** Epoch ms; used for ordering and timestamps. */
  timestamp: number
}

/**
 * Session lifecycle as seen by the UI:
 *   idle        nothing started yet
 *   connecting  opening the socket / authenticating
 *   generating  connected, patient is being generated by the AI (show loader)
 *   active      patient ready, chat is live (heartbeat animates)
 *   analyzing   end requested; awaiting the server's session analysis
 *   ended       session closed by the user
 *   error       connection/auth failure
 */
export type SessionPhase =
  | 'idle'
  | 'connecting'
  | 'generating'
  | 'active'
  | 'analyzing'
  | 'ended'
  | 'error'

/**
 * Specialty values accepted by the backend `start_session` event. These mirror
 * `SessionSpecialtyEnum` on the server exactly; the dashboard's lowercase ids
 * (e.g. "cardiology") are mapped to these before emitting.
 */
export type SessionSpecialty =
  | 'TRAUMATOLOGY'
  | 'CARDIOLOGY'
  | 'EMERGENCY_MEDICINE'

/** Payload for the `start_session` event (mirrors backend StartSessionDto). */
export interface StartSessionPayload {
  specialty: SessionSpecialty
}

/**
 * Per-turn vitals + evaluation the patient emits after every reply (mirrors
 * backend `PatientVitalsType`). `answerAccuracy` and `shortFeedback` form the
 * live evaluation; the UI tracks `answerAccuracy` over time like a chess eval.
 */
export interface PatientVitals {
  heartRate: number
  bloodPressure: string
  spO2: number
  painLevel: number
  patientStatus: string
  /** Running diagnostic-accuracy score (0–100), updated each turn. */
  answerAccuracy: number
  /** One-line coaching note on the trainee's latest move. */
  shortFeedback: string
}

/**
 * The full generated patient (mirrors backend `PatientInitialInfoType`): the
 * per-turn vitals plus the static profile. `condition` is the diagnosis target,
 * so the UI deliberately does NOT surface it during the consultation.
 */
export interface PatientProfile extends PatientVitals {
  patientName: string
  patientAge: number
  patientGender: string
  weight: number
  knownAllergies: string
  condition: string
}

/** Payload for the `session:start` event once the patient is generated. */
export interface SessionStartedPayload {
  /** The patient's opening line, shown as the first patient message. */
  message: string
  patient: PatientProfile
}

/** Payload for the `chat:done` event after the patient answers a message. */
export interface ChatDonePayload {
  /** The patient's reply, shown as a patient message. */
  outputMessage: string
  /** Refreshed vitals + evaluation for this turn. */
  patient: PatientVitals
}

export interface ReviewDiagnosis {
  correct: boolean
  actualCondition: string
  traineeDiagnosis: string
  notes: string
}

export interface FinalReview {
  overallPerformance: string
  whatWentWell: string[]
  whatCouldBeImproved: string[]
  keyLearningPoints: string[]
  finalScore: number
  scoreJustification: string
  diagnosis: ReviewDiagnosis
}

export interface SessionEndPayload {
  review: FinalReview
  score: number
  stepScores: number[]
  patientSurvived: boolean
  durationSeconds: number
  finalDiagnosis: string
}

/** A one-tap clinical prompt shown above the composer. */
export interface QuickAction {
  id: string
  /** Short button label. */
  label: string
  /** The doctor message sent when the action is tapped. */
  prompt: string
  /** Key into the icon set rendered by QuickActions. */
  icon: 'history' | 'vitals' | 'pain' | 'meds' | 'exam' | 'labs'
}
